language: cpp

compiler: clang

before_install:
    - git submodule update --init --recursive

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libclang1 llvm-3.4-dev libclang-common-3.4-dev libclang-3.4-dev clang-3.4-dev
    - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi
    - if [ "$CXX" == "clang++" ]; then export CXXFLAGS="-std=c++11 -stdlib=libc++"; fi

before_script: mkdir build && cd build && cmake ..

script: make

os:
    - linux
    - osx
