language: cpp

compiler: clang

before_install:
    - git submodule update --init --recursive

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libclang1 llvm-3.4-dev libclang-common-3.4-dev libclang-3.4-dev clang-3.4-dev
    - if [ "$CXX" == "clang++" ]; then export CXXFLAGS="-std=c++11 -stdlib=libc++"; fi

before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=clang++ ..

script: make

os:
    - linux
    - osx
